from nltk import corpus
from nltk.tokenize import RegexpTokenizer
from HTMLParser import HTMLParser
import re
import string
from nltk.stem.porter import *

REPLACEMENT_WORDS = [
    "Editing by", "editing by", "Editing By",
    "Reporting By", "Reporting by", "reporting by",
    "Compiled by", "compiled by", "Compiled By",
    "Writing by", "Writing By", "writing by",
    "U.S.", "U.N.",
    "(RNS)",
    "BERLIN:",  "BIRMINGHAM:",
    "LISBON:",  "MARSEILLE:",
    "PUTRAJAYA:",   "BERNE:",
    "DALLAS:",
    "DHAKA:",
    "SYDNEY:",
    "LARKIN:",
    "INCHEON:",
    "KUCHING:",
    "TOKYO:",
    "MUKAH:",
    "EASTBOURNE:",
    "MUGELLO:",
    "LIVERPOOL:",
    "SUBANG:",
    "MILAN:",
    "London:",
    "SERDANG:",
    "MONTREAL:",
    "KLUANG:",
    "BELGRADE:",
    "JAKARTA:",
    "MOSCOW:",
    "Naypyitaw:",
    "MANCHESTER:",
    "STOCKHOLM:",
    "KLANG:",
    "SEPANG:",
    "BRUSSELS:",
    "WENTWORTH:",
    "LANGKAWI:",
    "REMBAU:",
    "SINGAPORE:",
    "ODENSE:",
    "209:",
    "PALEMBANG:",
    "TAIPING:",
    "PARIS:",
    "SEREMBAN:",
    "WASHINGTON:",
    "KABUL:",
    "LAUSANNE:",
    "KAJANG:",
    "KUANTAN:",
    "LYON:",
    "SIBU:",
    "GUANGZHOU:",
    "JOHANNESBURG:",
    "MONACO:",
    "PEKAN:",
    "VERSAILLES:",
    "KARACHI:",
    "PHUKET:",
    "MADRID:",
    "KINGSTON:",
    "NUERBURGRING:",
    "IPOH:",
    "KANGAR:",
    "SHANGHAI:",
    "GLASGOW:",
    "ROME:",
    "MEMPHIS:",
    "YANGON:",
    "ZURICH:",
    "MIAMI:",
    "PENANG:",
    "MUNICH:",
    "SILVERSTONE:",
    "PHOENIX:",
    "PONTIAN:",
    "NYAPYITAW:",
    "SELAYANG:",
    "TORONTO:",
    "MARANG:",
    "ZAGREB:",
    "MELBOURNE:",
    "NAYPYITAW:",
    "LONDON:",
    "NICOSIA:",
    "EXCLUSIVE:",
    "SALVADOR:",
    "BANGKOK:",
    "MANILA:",
    "PERAI:",
    "DUBAI:",
    "INDIANAPOLIS:",
    "Name:",
    "KUALALUMPUR:",
    "BUDAPEST:",
    "BARCELONA:",
    "BEIJING:",
    "COPENHAGEN:",
    "KANAGR:",
    "ISTANBUL:",
    "BRASILIA:",
    "MALACCA:",
    "VIENNA:",
    "USEFUL:",
    "PENANG:",
    "BERLIN:",
    "PAYERNE:",
    "DALLAS:",
    "Update:",
    "SYDNEY:",
    "GAZA:",
    "YANGON:",
    "KAWASAKI:",
    "CHICAGO:",
    "BOGOTA:",
    "REVAMP:",
    "ANKARA:",
    "MINISCULE:",
    "DAKAR:",
    "WARSAW:",
    "SOFIA:",
    "KUNSHAN:",
    "MILAN:",
    "LAGOS:",
    "Hagerman:",
    "HOMESTEAD:",
    "MONTREAL:",
    "Warren:",
    "TASHKENT:",
    "Howard:",
    "agic:",
    "JAKARTA:",
    "MOSCOW:",
    "WARWICK:",
    "HANOI:",
    "DETROIT:",
    "Omidyar:",
    "STOCKHOLM:",
    "AMMAN:",
    "BRUSSELS:",
    "BUDAPEST:",
    "SINGAPORE:",
    "DENVER:",
    "CINZANA:",
    "AMSTERDAM:",
    "GENEVA:",
    "PARIS:",
    "WASHINGTON:",
    "UPDATE:",
    "KABUL:",
    "YOKOHAMA:",
    "BUCHAREST:",
    "JERUSALEM:",
    "OSAKA:",
    "OTTAWA:",
    "JOHANNESBURG:",
    "inFamous:",
    "MONACO:",
    "TAIPEI:",
    "DHAKA:",
    "SANTIAGO:",
    "MADRID:",
    "UNCONSTITUTIONAL:",
    "PHILADELPHIA:",
    "TEHRAN:",
    "EDINBURGH:",
    "Updated:",
    "SEOUL:",
    "SHANGHAI:",
    "MINNEAPOLIS:",
    "BENDY:",
    "ROME:",
    "ATLANTA:",
    "SEATTLE:",
    "Infamous:",
    "CARACAS:",
    "ZURICH:",
    "MIAMI:",
    "ISLAMABAD:",
    "SOCHI:",
    "MUNICH:",
    "HAVANA:",
    "FRANKFURT:",
    "BEIJING:",
    "RIGA:",
    "WELLINGTON:",
    "OSLO:",
    "TALLINN:",
    "TORONTO:",
    "KAMPALA:",
    "PITTSBURGH:",
    "BOSTON:",
    "MELBOURNE:",
    "REUTERS:",
    "LONDON:",
    "NAIROBI:",
    "HELSINKI:",
    "TOKYO:",
    "LUXEMBOURG:",
    "BANGKOK:",
    "SARAJEVO:",
    "MANILA:",
    "HAMBURG:",
    "Desouza:",
    "SHENZHEN:",
    "DUBAI:",
    "BARCELONA:",
    "Wong:",
    "COPENHAGEN:",
    "KINSHASA:",
    "FRANCISCO:",
    "ISTANBUL:",
    "BRASILIA:",
    "MUMBAI:",
    "BAGHDAD:",
    "BANGALORE:",
    "VIENNA:",
    "NEW YORK:",
    "Haiti ",
    "PARIS ",
    "Malaysia ",
    "MINNEAPOLIS ",
    "Hawaii ",
    "MIAMI ",
    "JANEIRO ",
    "Indonesia ",
    "Bank ",
    "NASHVILLE ",
    "Denmark ",
    "PHILADELPHIA ",
    "Jamaica ",
    "AMMAN ",
    "LONDON ",
    "CHARLOTTE ",
    "FRANCISCO ",
    "YORK ",
    "DUBLIN ",
    "Washington ",
    "BEIJING ",
    "BERLIN ",
    "SEATTLE ",
    "THAILAND ",
    "KENYA ",
    "Utah ",
    "of ",
    "Ireland ",
    "Bhutan ",
    "Morocco ",
    "ANGELES ",
    "BALTIMORE ",
    "Jordan ",
    "Syria ",
    "Brazil ",
    "ORONTO ",
    "Texas ",
    "BOSTON ",
    "Canada ",
    "ROME ",
    "England ",
    "LOUIS ",
    "Myanmar ",
    "TOWN ",
    "Iowa ",
    "ORLANDO ",
    "CITY ",
    "Israel ",
    "BANGKOK ",
    "CLEVELAND ",
    "Afghanistan ",
    "Kenya ",
    "Zambia ",
    "TUNISIA ",
    "Spain ",
    "Iraq ",
    "HOUSTON ",
    "YouTubeMOSCOW ",
    "India ",
    "INDIANAPOLIS ",
    "ATLANTA ",
    "BEIRUT ",
    "CAIRO ",
    "ISTANBUL ",
    "Italy ",
    "GENEVA ",
    "CHICAGO ",
    "France ",
    "ISLAMABAD ",
    "Service ",
    "DELHI ",
    "Pakistan ",
    "Tanzania ",
    "Mexico ",
    "Germany ",
    "Ohio ",
    "HONOLULU ",
    "Ukraine ",
    "WASHINGTON ",
    "Liberia ",
    "ORLEANS ",
    "JERUSALEM ",
    "TORONTO ",
]

ADDITIONAL_STOP_WORDS = [
    "a", "about", "above", "above", "across", "after", "afterwards", "again", "against", "all", "almost", "alone", "along", "already", "also","although","always","am","among", "amongst", "amoungst", "amount",  "an", "and", "another", "any","anyhow","anyone","anything","anyway", "anywhere", "are", "around", "as",  "at", "back","be","became", "because","become","becomes", "becoming", "been", "before", "beforehand", "behind", "being", "below", "beside", "besides", "between", "beyond", "bill", "both", "bottom","but", "by", "call", "can", "cannot", "cant", "co", "con", "could", "couldnt", "cry", "de", "describe", "detail", "do", "done", "down", "due", "during", "each", "eg", "eight", "either", "eleven","else", "elsewhere", "empty", "enough", "etc", "even", "ever", "every", "everyone", "everything", "everywhere", "except", "few", "fifteen", "fify", "fill", "find", "fire", "first", "five", "for", "former", "formerly", "forty", "found", "four", "from", "front", "full", "further", "get", "give", "go", "had", "has", "hasnt", "have", "he", "hence", "her", "here", "hereafter", "hereby", "herein", "hereupon", "hers", "herself", "him", "himself", "his", "how", "however", "hundred", "ie", "if", "in", "inc", "indeed", "interest", "into", "is", "it", "its", "itself", "keep", "last", "latter", "latterly", "least", "less", "ltd", "made", "many", "may", "me", "meanwhile", "might", "mill", "mine", "more", "moreover", "most", "mostly", "move", "much", "must", "my", "myself", "name", "namely", "neither", "never", "nevertheless", "next", "nine", "no", "nobody", "none", "noone", "nor", "not", "nothing", "now", "nowhere", "of", "off", "often", "on", "once", "one", "only", "onto", "or", "other", "others", "otherwise", "our", "ours", "ourselves", "out", "over", "own","part", "per", "perhaps", "please", "put", "rather", "re", "same", "see", "seem", "seemed", "seeming", "seems", "serious", "several", "she", "should", "show", "side", "since", "sincere", "six", "sixty", "so", "some", "somehow", "someone", "something", "sometime", "sometimes", "somewhere", "still", "such", "system", "take", "ten", "than", "that", "the", "their", "them", "themselves", "then", "thence", "there", "thereafter", "thereby", "therefore", "therein", "thereupon", "these", "they", "thickv", "thin", "third", "this", "those", "though", "three", "through", "throughout", "thru", "thus", "to", "together", "too", "top", "toward", "towards", "twelve", "twenty", "two", "un", "under", "until", "up", "upon", "us", "very", "via", "was", "we", "well", "were", "what", "whatever", "when", "whence", "whenever", "where", "whereafter", "whereas", "whereby", "wherein", "whereupon", "wherever", "whether", "which", "while", "whither", "who", "whoever", "whole", "whom", "whose", "why", "will", "with", "within", "without", "would", "yet", "you", "your", "yours", "yourself", "yourselves", "the",
    'secondly',
    'all',
    'consider',
    'whoever',
    'results',
    'four',
    'edu',
    'go',
    'causes',
    'seemed',
    'rd',
    'certainly',
    'whens',
    'vs',
    'ts',
    'to',
    'asking',
    'present',
    'th',
    'under',
    'sorry',
    'promptly',
    'as',
    'mug',
    'sent',
    'far',
    'mg',
    'every',
    'yourselves',
    'well',
    'went',
    'did',
    'forth',
    'theyve',
    'try',
    'p',
    'shows',
    'noted',
    'added',
    'itll',
    'ill',
    'says',
    'youd',
    'yourself',
    'd',
    'past',
    'likely',
    'invention',
    'further',
    'even',
    'index',
    'what',
    'appear',
    'giving',
    'section',
    'brief',
    'goes',
    'sup',
    'new',
    'poorly',
    'ever',
    'cmon',
    'whose',
    'youd',
    'respectively',
    'never',
    'here',
    'let',
    'others',
    'hadnt',
    'along',
    'arent',
    'suggest',
    'obtained',
    'ref',
    'k',
    'allows',
    'proud',
    'id',
    'resulting',
    'howbeit',
    'hed',
    'usually',
    'whereupon',
    'im',
    'changes',
    'thats',
    'hither',
    'via',
    'followed',
    'merely',
    'while',
    'put',
    'ninety',
    'vols',
    'viz',
    'ord',
    'readily',
    'everybody',
    'use',
    'from',
    'would',
    'contains',
    'two',
    'next',
    'few',
    'therefore',
    'taken',
    'themselves',
    'thru',
    'tell',
    'more',
    'knows',
    'mr',
    'becomes',
    'hereby',
    'herein',
    'aint',
    'particular',
    'known',
    'wholl',
    'must',
    'me',
    'none',
    'wouldnt',
    'f',
    'this',
    'ml',
    'oh',
    'anywhere',
    'nine',
    'can',
    'theirs',
    'following',
    'my',
    'example',
    'indicated',
    'give',
    'didnt',
    'indicates',
    'something',
    'want',
    'arise',
    'information',
    'needs',
    'end',
    'rather',
    'meanwhile',
    'makes',
    'how',
    'instead',
    'okay',
    'tried',
    'may',
    'stop',
    'after',
    'eighty',
    'different',
    'hereupon',
    'ff',
    'date',
    'such',
    'a',
    'thered',
    'third',
    'whenever',
    'maybe',
    'appreciate',
    'q',
    'ones',
    'so',
    'specifying',
    'allow',
    'keeps',
    'thats',
    'six',
    'help',
    'dont',
    'indeed',
    'over',
    'werent',
    'mainly',
    'soon',
    'course',
    'through',
    'looks',
    'still',
    'its',
    'refs',
    'before',
    'thank',
    'hes',
    'selves',
    'inward',
    'fix',
    'actually',
    'better',
    'whether',
    'willing',
    'thanx',
    'ours',
    'might',
    'havent',
    'then',
    'non',
    'someone',
    'somebody',
    'thereby',
    'auth',
    'youve',
    'they',
    'not',
    'now',
    'nor',
    'nos',
    'wont',
    'several',
    'hereafter',
    'always',
    'reasonably',
    'whither',
    'shes',
    'sufficiently',
    'each',
    'found',
    'entirely',
    'mustnt',
    'isnt',
    'mean',
    'everyone',
    'significantly',
    'doing',
    'ed',
    'eg',
    'related',
    'owing',
    'ex',
    'substantially',
    'our',
    'beyond',
    'couldnt',
    'out',
    'shown',
    'them',
    'furthermore',
    'since',
    'research',
    'looking',
    're',
    'seriously',
    'shouldnt',
    'theyll',
    'got',
    'cause',
    'thereupon',
    'youre',
    'million',
    'given',
    'quite',
    'whatll',
    'que',
    'besides',
    'x',
    'ask',
    'anyhow',
    'beginning',
    'g',
    'could',
    'similarly',
    'tries',
    'keep',
    'w',
    'ltd',
    'hence',
    'onto',
    'think',
    'first',
    'already',
    'seeming',
    'omitted',
    'thereafter',
    'thereof',
    'one',
    'done',
    'approximately',
    'another',
    'miss',
    'awfully',
    'doesnt',
    'little',
    'necessarily',
    'zeroa',
    'their',
    'accordingly',
    'least',
    'name',
    'anyone',
    'indicate',
    'too',
    'hundred',
    'gives',
    'mostly',
    'behind',
    'nobody',
    'took',
    'immediate',
    'regards',
    'somewhat',
    'kept',
    'believe',
    'herself',
    'than',
    'heres',
    'begins',
    'b',
    'unfortunately',
    'showed',
    'accordance',
    'gotten',
    'second',
    'i',
    'r',
    'were',
    'toward',
    'are',
    'and',
    'youre',
    'ran',
    'thoughh',
    'beforehand',
    'say',
    'unlikely',
    'have',
    'need',
    'seen',
    'seem',
    'saw',
    'any',
    'relatively',
    'zero',
    'thoroughly',
    'latter',
    'that',
    'downwards',
    'aside',
    'thorough',
    'predominantly',
    'also',
    'take',
    'which',
    'begin',
    'exactly',
    'unless',
    'shall',
    'who',
    'wheres',
    'most',
    'eight',
    'but',
    'significant',
    'nothing',
    'why',
    'sub',
    'kg',
    'especially',
    'noone',
    'later',
    'm',
    'km',
    'yours',
    'heres',
    'youll',
    'definitely',
    'shed',
    'normally',
    'came',
    'saying',
    'particularly',
    'show',
    'anyway',
    'ending',
    'thatll',
    'fifth',
    'specifically',
    'outside',
    'should',
    'only',
    'going',
    'specify',
    'announce',
    'itd',
    'thereve',
    'do',
    'his',
    'above',
    'get',
    'between',
    'overall',
    'truly',
    'theyd',
    'cannot',
    'hid',
    'nearly',
    'words',
    'despite',
    'during',
    'him',
    'regarding',
    'qv',
    'h',
    'twice',
    'she',
    'contain',
    'wont',
    'where',
    'thanks',
    'ignored',
    'up',
    'namely',
    'sec',
    'anyways',
    'thatve',
    'throug',
    'best',
    'wonder',
    'said',
    'away',
    'currently',
    'please',
    'ups',
    'enough',
    'theres',
    'various',
    'hopefully',
    'affecting',
    'probably',
    'neither',
    'across',
    'available',
    'we',
    'recently',
    'useful',
    'importance',
    'however',
    'meantime',
    'come',
    'both',
    'c',
    'last',
    'wasnt',
    'thou',
    'many',
    'wouldnt',
    'thence',
    'according',
    'against',
    'etc',
    's',
    'became',
    'com',
    'cant',
    'otherwise',
    'among',
    'presumably',
    'co',
    'afterwards',
    'seems',
    'ca',
    'whatever',
    'alone',
    'couldnt',
    'moreover',
    'throughout',
    'considering',
    'sensible',
    'pp',
    'described',
    'its',
    'three',
    'been',
    'quickly',
    'whom',
    'much',
    'wherein',
    'ah',
    'whod',
    'hardly',
    'itd',
    'wants',
    'corresponding',
    'latterly',
    'concerning',
    'else',
    'hers',
    'former',
    'those',
    'myself',
    'novel',
    'look',
    'unlike',
    'these',
    'means',
    'tip',
    'thereto',
    'value',
    'n',
    'will',
    'near',
    'taking',
    'theres',
    'seven',
    'whereafter',
    'almost',
    'wherever',
    'is',
    'thus',
    'it',
    'cant',
    'itself',
    'im',
    'in',
    'affected',
    'ie',
    'id',
    'if',
    'containing',
    'anymore',
    'perhaps',
    'insofar',
    'make',
    'same',
    'clearly',
    'beside',
    'when',
    'potentially',
    'widely',
    'gets',
    'werent',
    'used',
    'y',
    'slightly',
    'see',
    'somewhere',
    'I',
    'upon',
    'effect',
    'uses',
    'hell',
    'wheres',
    'recent',
    'off',
    'whereby',
    'largely',
    'nevertheless',
    'whole',
    'nonetheless',
    'well',
    'anybody',
    'obviously',
    'without',
    'comes',
    'very',
    'the',
    'self',
    'lest',
    'world',
    'shell',
    'just',
    'less',
    'being',
    'able',
    'therere',
    'liked',
    'greetings',
    'immediately',
    'regardless',
    'yes',
    'yet',
    'unto',
    'wed',
    'weve',
    'had',
    'except',
    'thousand',
    'lets',
    'has',
    'adj',
    'ought',
    'gave',
    'ts',
    'arent',
    'around',
    'whos',
    'possible',
    'usefully',
    'possibly',
    'five',
    'know',
    'using',
    'part',
    'apart',
    'abst',
    'nay',
    'necessary',
    'like',
    'follows',
    'theyre',
    'either',
    'become',
    'page',
    'towards',
    'therein',
    'whys',
    'www',
    'because',
    'old',
    'often',
    'successfully',
    'some',
    'somehow',
    'l',
    'sure',
    'shes',
    'specified',
    'home',
    've',
    'ourselves',
    'shant',
    'happens',
    'vol',
    'therell',
    'for',
    'affects',
    'though',
    'per',
    'everything',
    'does',
    'provides',
    'tends',
    't',
    'be',
    'run',
    'obtain',
    'nowhere',
    'although',
    'by',
    'on',
    'about',
    'ok',
    'anything',
    'getting',
    'of',
    'v',
    'o',
    'whomever',
    'whence',
    'plus',
    'act',
    'consequently',
    'or',
    'seeing',
    'own',
    'whats',
    'formerly',
    'previously',
    'somethan',
    'into',
    'within',
    'shed',
    'due',
    'down',
    'appropriate',
    'right',
    'primarily',
    'theyd',
    'cs',
    'whos',
    'your',
    'hows',
    'her',
    'hes',
    'aren',
    'apparently',
    'there',
    'biol',
    'pages',
    'hed',
    'inasmuch',
    'inner',
    'way',
    'resulted',
    'was',
    'himself',
    'elsewhere',
    'ive',
    'becoming',
    'amongst',
    'back',
    'hi',
    'etal',
    'line',
    'trying',
    'with',
    'he',
    'usefulness',
    'theyre',
    'made',
    'wasnt',
    'wish',
    'j',
    'hasnt',
    'us',
    'until',
    'placed',
    'below',
    'un',
    'whim',
    'z',
    'similar',
    'wed',
    'strongly',
    'gone',
    'sometimes',
    'associated',
    'certain',
    'am',
    'an',
    'as',
    'sometime',
    'at',
    'et',
    'mrs',
    'inc',
    'again',
    'll',
    'no',
    'na',
    'whereas',
    'nd',
    'lately',
    'til',
    'other',
    'you',
    'really',
    'whats',
    'showns',
    'briefly',
    'beginnings',
    'welcome',
    'lets',
    'important',
    'serious',
    'e',
    'together',
    'having',
    'u',
    'were',
    'everywhere',
    'hello',
    'once',
    "also",
    "uk",
    "www",
    "html",
    "and",
    "reuters",
    "theguardian",
    "washington",
    "ap",
    "afp",
    "relaxnews",
    "nbcnews",
    "nbc",
    "bbc",
    "rtrfaithworld",
    "faithworld",
    "rns",
    "mr",
    "ms",
    "f",
    "v",
    "k",
    "n",
    "o",
    "ll",
    "walletpop",

    # people name
    "kj",
    "dellantonia",
    "bengaluru",
    "uk",
    "pct",

    # Nation
    "lewes",
    "england",
    "us",
    "u",
    "un",
    "ul",
    "lo",

    # Place in California
    "pasadena",
    "madison",
    "dallas",
    "monaco",

    # Unnecessary words
    "yesterday",
    "ys",
    "mg",
    "end",
    "nzwili",
    'amb',
    'salkin',
    'gibson'
]

##################################
# Extend stop words              #
#################################
STOP_WORDS = corpus.stopwords.words("english")
TOKENIZER = RegexpTokenizer(r'\w+')
STOP_WORDS.extend(ADDITIONAL_STOP_WORDS)


class MLStripper(HTMLParser):
    def __init__(self):
        self.reset()
        self.fed = []

    def handle_data(self, data):
        self.fed.append(data)

    def get_data(self):
        return "".join(self.fed)


class NormalizationText():
    @staticmethod
    def remove_html_tag(text):
        """
        Remove html tag in text. For example, <html>, <a>, <div>
        :param text:
        :return:
        """
        if text:
            s = MLStripper()
            s.feed(text)
            return s.get_data()
        else:
            return ""

    @staticmethod
    def normalize_to_unicode(text):
        if type(text) is not unicode:  # If the input is already unicode, no need to decode again
            try:
                text = text.decode('utf-8')  # Might throw exception on cp1252 encoding
            except UnicodeDecodeError:
                text = text.decode('cp1252')  # This should be the most plausibly correct encoding, since it's not UTF8
                                              # Note that cp1252 will not fail on any input

        # These cases happen only when we are given unicode as input
        # This is because \xNN can happen only with 'charmap' decoding, which we don't do above
        text = text.replace(u'\x19',"'")
        text = text.replace(u'\x14',"")

        text = text.replace(u'\x93', '"')
        text = text.replace(u'\x94', '"')
        text = text.replace(u'\x96', '-')
        text = text.replace(u'\x97', '-')
        text = text.replace(u'\x91', "'")
        text = text.replace(u'\x92', "'")
        text = text.replace(u'\xa0', ' ')
        text = re.sub('[\x80-\xff]', '', text)

        # These cases are properly encoded unicode characters (either UTF-8 or cp1252)
        text = text.replace(u'\u201c', '"')
        text = text.replace(u'\u201d', '"')
        text = text.replace(u'\u2013', '-')
        text = text.replace(u'\u2014', '-')
        text = text.replace(u'\u2018', "'")
        text = text.replace(u'\u2019', "'")

        # Return the text as unicode
        return text

    @staticmethod
    def preprocess(text):
        def strip_punctuation(str):
            # deleted_not_dot = string.punctuation.replace('.', '')
            regex = re.compile('[%s]' % re.escape(string.punctuation))
            return regex.sub('', str)
        text = strip_punctuation(text)

        for replace_word in REPLACEMENT_WORDS:
            text = text.replace(replace_word, " ")

        text = re.sub(r"[^A-Za-z0-9(),!?\'\`]", " ", text)
        text = re.sub(r"\'s", " \'s", text)
        text = re.sub(r"\'ve", " \'ve", text)
        text = re.sub(r"n\'t", " n\'t", text)
        text = re.sub(r"\'re", " \'re", text)
        text = re.sub(r"\'d", " \'d", text)
        text = re.sub(r"\'ll", " \'ll", text)
        text = re.sub(r",", " , ", text)
        text = re.sub(r"!", " ! ", text)
        text = re.sub(r"\(", " \( ", text)
        text = re.sub(r"\)", " \) ", text)
        text = re.sub(r"\?", " \? ", text)
        text = re.sub(r"\s{2,}", " ", text)

        text = NormalizationText.normalize_to_unicode(text).strip()
        stemmer = PorterStemmer()
        content = " ".join([stemmer.stem(w) for w in TOKENIZER.tokenize(text) if w.lower() not in STOP_WORDS and len(w) < 15])
        return content.lower()
